### ISSUE TITLE
页面内点击链接切换Action时有时失效

### ISSUE THREAD

**Issue by mytharcher** [erik168/ER#1]
操作步骤：
1. 默认路径进入`/module`；
2. 根据逻辑跳转到指定Action`/module/first`；
3. 点击链接跳转到`/module/second`；
4. 点击链接跳回`/module/first`或`/module`，_在此步均无法正常跳回_。

追查代码后发现任何点击链接的跳转不会记录新的链接到变量`currentLocation`中，由此引发上述问题。

建议修改`er.locator.js`第136行，加入`updateLocation( loc )`的处理更新当前地址的记录。

**Comment by erik168** [comment]
resolved
