### ISSUE TITLE
label in BoxControl?

### ISSUE THREAD

**Issue by mytharcher** [erik168/ER#10]
`BoxControl.js`中，如果render过一次以后，再次render时不会走创建label的分支（line 150），然后局域变量`label`是未赋值状态，调用`innerHTML`报`undefined`（line 161）。

**Comment by leeight** [comment]
你们在啥项目中使用这个版本的ER？

**Comment by mytharcher** [comment]
union里esui一直在用，er也准备升到最新。

**Comment by leeight** [comment]
fixed.
