### ISSUE TITLE
加载器队列需要跳出控制

### ISSUE THREAD

**Issue by mytharcher** [erik168/ER#2]
当一个加载队列中的某个加载器出现某些业务问题时，无法提前结束当前流程，跳转到界面渲染的处理。`stop()`只能暂停，但不能跳出。希望能增加一个`exit()`方法，以便控制加载流程。

**Comment by erik168** [comment]
start掉就能跳出了

**Comment by mytharcher** [comment]
我说的是跳出整个Loader队列，不只是提前结束当前Loader。而且start也无法结束当前Loader。
